<?php declare(strict_types = 1);

/**
 * @file
 * Primary module hooks for Custom theme module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function custom_theme_page_attachments_alter(array &$attachments): void {
  // Conditionally remove an asset.
  
  if (in_array('core/jquery', $attachments['#attached']['library'])) {
    $index = array_search('core/jquery', $attachments['#attached']['library']);
    unset($attachments['#attached']['library'][$index]);
  }
}
